---
- name: Update Rust to the latest version
  command: rustup update

# cargo
- name: Install Rust tools with cargo
  command: "cargo install {{ item.name }}"
  loop: "{{ cargo_packages }}"
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/{{ item.executable | default(item.name) }}"
